### PR TITLE
Add Capability.VOTE

### PR DESCRIPTION
**Pull request by ManfredKarrer**

### CODE REVIEW

**Review by sqrrm — APPROVED** [review]
utACK

**Review by cbeams — APPROVED** [review]
utACK

I think with changes like these, we can probably get into a mode of waiting to add the functionality until its actually necessary to do so. It again feels like we're doing "too much work" here, having to run around to N different repositories every time a tiny change like this is made. That's to be expected of course, after the repo split, and it's exactly inconveniences like this that create incentives to keep refactoring and redesigning things toward the kind of high cohesion and low coupling that allow us to _not_ have to make these kind of micro-changes everywhere all the time.

What's not clear to me in this case is whether this change actually needs to be made now, or if you were just doing it "for good measure", @ManfredKarrer, i.e. to just keep everything in sync for its own sake. Would it have been just as reasonable here, to wait to add the `VOTE` capability until such time (if ever) it became necessary for the statsnode to know about it? Or would something be "broken" if it remained missing?

I'll merge this after other, lower-level `VOTE`-related PRs have been merged, esp bisq-network/bisq-common#10.

**Comment by ManfredKarrer** [comment]
Basically as long the DAO stuff is not used it would be not needed, but I think to merge that is less effort and risk as to keep it for later and maybe forget. It is not so easy to spot that as peers will just get rejected in the p2p network.

**Comment by sqrrm** [comment]
I think it makes sense to add it now. This ties in with the work currently being done and makes most sense to review and follow in general if it's done at the same time. If it was added at a later date it would be harder to find when looking back at the other PRs.

**Review by sqrrm — APPROVED** [review]

**Pull request merged**
